name: Collecte Bourse
on:
  schedule:
    - cron: '30 16 * * 1-5' # Du lundi au vendredi à 16h30 UTC
  workflow_dispatch: # Permet de lancer à la main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install libs
        run: pip install -r requirements.txt
      - name: Run script
        run: python collecte_bourse.py
      - name: Commit data
        run: |
          git config --global user.name 'Robot'
          git config --global user.email 'robot@github.com'
          git add bourse_casablanca_historique.csv
          git commit -m "Auto-update $(date)" || exit 0
          git push
